---
- name: Initial Cloud Setup
  hosts: towers
  #hosts: localhost
  #become: true
  gather_facts: no

  vars:
    GUID: "{{ lookup('ENV','GUID') }}"
    HOME: "{{ lookup('ENV','HOME') }}"

  environment:
    OS_CLOUD: "{{ lookup('ENV','GUID') }}-project"
  pre_tasks:
    - name: Ping hosts
      ping:

    - name: Check hostname
      shell: "hostname -a"

    - name: Checking host ipaddress
      shell: "ip add"

  roles:
    - role: prep_node_for_osp
    