---
- name: Initial Cloud Setup
  hosts: localhost
  gather_facts: yes

  vars:
    GUID: "{{ lookup('ENV','GUID') }}"
    HOME: "{{ lookup('ENV','HOME') }}"

  environment:
    OS_CLOUD: "{{ lookup('ENV','GUID') }}-project"

  roles:
    - role: prep_node_for_osp
    