---
- name: Initial Cloud Setup
  hosts: localhost
  #hosts: localhost
  become: true
  connection: local
  gather_facts: no

  vars:
    #GUID: "{{ lookup('ENV','GUID') }}"
    GUID: "d1a1"
    HOME: "/home/devops"

  environment:
    OS_CLOUD: "d1a1-project"
  #pre_tasks:
  # tasks:
  #   - name: Ping hosts
  #     ping:

  #   - name: Check hostname
  #     shell: "hostname -a"

  #   - name: Who Am I
  #     shell: "whoami"

  #   - name: Checking host ipaddress
  #     shell: "ip add"

  roles:
    - role: prep_node_for_osp
    