---
- name: Initial Cloud Setup
  hosts: localhost
  #hosts: localhost
  #become: true
  connection: local
  gather_facts: no

  vars:
    #GUID: "{{ lookup('ENV','GUID') }}"
    GUID: "d1a1"
    HOME: "{{ lookup('ENV','HOME') }}"

  environment:
    OS_CLOUD: "{{ GUID }}-project"
  pre_tasks:
    - name: Ping hosts
      ping:

    - name: Check hostname
      shell: "hostname -a"

    - name: Checking host ipaddress
      shell: "ip add"

  # roles:
  #   - role: prep_node_for_osp
    