---
- name: Ensure devops user on control node
  user:
    name: "{{ user._name | default('devops')}}"
    shell: /bin/bash
    uid: "{{ user._id | default('1002') }}"
    comment: "DevOps Automation Service Account"
    generate_ssh_key: yes
    ssh_key_bits: "{{ ssh_key_bits | default('4096') }}"
    ssh_key_file: .ssh/id_rsa
    password: "{{ user._passwd | default('$6$CXQp3tNaViAe0WDG$K/.CEzpzkBqL1UAqXwDddvP5CvmAkBohmy.IB47XqiosBu2tB31bPOWdTqn8xQ5hAP/V4ExJxXVXrd0U1QKlp0')}}" # encrypted password default is redhat
    update_password: always
    state: present
  loop: "{{ user }}"
  loop_control:
    loop_var: user

- name: Adding user "{{ user._name }}" to Sudo configuration on frontend, database and app servers
  copy:
    content: "{{user._name}}  ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ user._name }}_service_account"
  when: "ansible_hostname not in 'control'"

- name: Disabling SSH root user login.
  replace:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin yes"
    replace: "^PermitRootLogin no"
    validate: sshd -t
  notify: restart_sshd
  when: "ansible_hostname not in 'control'"

- name: Disabling SSH Password Based Authentication
  replace:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication yes"
    replace: "^PasswordAuthentication no"
    validate: sshd -t
  notify: restart_sshd
  when: "ansible_hostname not in 'control'"

- name: Acquiring DNS seerver IP "listen_addresses
  shell: "ip a s eth0 | grep 'inet[[:space:]]' | awk '{print $2}' | awk -F'/' '{print $1}'"
  register: _dns_nameserver_ip
  when: "ansible_hostname == 'control'"

- name: Configure DNS on hosts
  lineinfile:
    path: "/etc/sysconfig/network-scripts/ifcfg-eth0"
    line: "{{ item }}"
  loop:
    - "PEERDNS=no"
    - "DNS1={{ _dns_nameserver_ip }}"
  when: "ansible_hostname != 'control'"
  register: _dns_configured

- name: Effecting DNS Configuration
  notify: restart_network_manager
  when: _dns_configured.changed | bool