---
- name: Collection instance info
  os_server_info:
    cloud: "{{ GUID }}-project"
  register: instances

- name: Build In-Memory inventory
  add_host:
    host: "{{ instance.name }}.{{ internal_domain }}"
    group: "{{ instance.metadata.AnsibleGroup }}"
    ansible_host: "{{ instance.private_v4 }}"
    ssh_private_key_file: "{{ HOME }}/.ssh/{{ GUID }}key.pem"
  when: instance.metadata.AnsibleGroup == "osp_instances"
  loop: "{{ instances.openstack_servers }}"
  loop_control:
    loop_var: instance

- name: Print current hosts
  debug:
    var: groups

- name: Verify OpenStack Instances
  hosts: "osp_instances"
  block:
    - name: Verify connectivity
      ping:
      register: output

    - debug:
        msg: "{{ output }}"