---
# - name: Install Catello Consumer Package for Satellite
#   yum: 
#     name: "{{ katello_package }}"
#     state: present
#     disable_gpg_check: true

# - name: Register System and Attach Subscription
#   redhat_subscription:
#     org_id: "{{ satellite_org }}"
#     activationkey: "{{ satellite_key }}"
#     auto_attach: yes
#     state: present

- name: Gather network facts
  setup:
    gather_subset:
      - 'network'
  delegate_facts: true
  delegate_to: localhost
  connection: local

- name: DNS IP updated
  lineinfile:
    state: present
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: "{{ item }}"
  loop:
    - PEERDNS=no
    - DNS1={{ hostvars.localhost.ansible_default_ipv4.address }}
  register: network_update

- name: restart network manager
  service:
    name: NetworkManager
    state: restarted
  when: network_update.changed | bool

- name: install katello-ca-consumer package
  yum:
    name: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
    state: present
    disable_gpg_check: true

- name: register system and attach subs
  redhat_subscription:
    state: present
    activationkey: "{{ satellite_key }}"
    org_id: "{{ satellite_org }}"
    auto_attach: true